### ISSUE TITLE
Timeline for code release

### ISSUE THREAD

**Issue by ChengHan111** [RuipingL/MISS#1]
Hi, thank you so much for the excellent work! I am wondering what is the timeline for code release, and where was this paper submitted to? Thank you!

**Comment by RuipingL** [comment]
hi @ChengHan111, thank you for your interest. I will release the code asap (maybe within two or three days). It's submitted to IEEE intelligent vehicle.

**Comment by ChengHan111** [comment]
Thank you for your information! I am looking forwards to it.

**Comment by RuipingL** [comment]
@ChengHan111 mostly done. Please check it out.

**Comment by ChengHan111** [comment]
Thank you! This is really helpful.
